name: Maven tests

on:
  pull_request_target:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Set up JDK 21
        uses: actions/setup-java@6a0805fcefea3d4657a47ac4c165951e33482018 # v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Run Maven tests
        env:
          TEST_TOKEN: ${{ secrets.TEST_TOKEN }}
        run: mvn test
